
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:8889/java_microservice?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

application:
  version: 1
  
#task-service:
#  ribbon:
#    listOfServers: http://localhost:8083/,http://localhost:8085/

#eureka:         #tells about the Eureka server details and its refresh time
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5
